### ISSUE TITLE
Code management

### ISSUE THREAD

**Issue by wlmitch** [cgi-paris-fs-comex/psa-template#14]
Here are some things to do :

- Project structure
  - separate resources into folders : js/css/html/images
- background.js : Is it usefull ?
-  popup.js
  - multiple `case: break` : Replace with an array
  - `location_m` is meaningless : Replace with a significant name
  - `optionData` is too long : Replace with a shorter name like `options` is sufficient
- option.js/html : Is it still useful ?
- options.js
  - `document.getElementById('...')` use jquery selector instead
  - line 13, multiple || : replace with an array
- options.html
  - `<select id="select-category">` content could be stored in an array in options.js
  - `<select id="select-samedi-a">` avoid duplicated content by using data stored in options.js ?

If we need parameters, maybe a "parameters.js" or "data.js" can be created to store arrays

To be continued ...

**Comment by pelus0** [comment]
concerning background, I need it to display popup.html because I use pageAction in manifest
